run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
  disable:
    - depguard    # Skip import restrictions for local packages
    - misspell    # Skip spell checking

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd